### ISSUE TITLE
About train_ppi_ec.csv.gz file

### ISSUE THREAD

**Issue by Seana4rd** [joanagoncalveslab/ELISL#1]
Dear authors,
    Thanks for your work on predicting SLs in cancer! However, when I tried to reproduce the reported results in the paper, I received an error stating'No such file or directory: './data/feature_sets/train_ppi_ec.csv.gz'. 
Additionally, I noticed that this file is not provided in the URL "https://doi.org/10.6084/m9.figshare.23607558". However, the URLs (Name2String and Unipror2String) are ineffective when I attempted to generate this PPI data from scratch following the recommended steps. 

   Consequently, could you provide this crucial file (**train_ppi_ec.csv.gz**)?

**Comment by yitepeli** [comment]
Dear @Seana4rd , 

We uploaded the file to the figshare (the last file).

Best

**Comment by Seana4rd** [comment]
Thank you!
