### ISSUE TITLE
About the results of the ELISL

### ISSUE THREAD

**Issue by Seana4rd** [joanagoncalveslab/ELISL#2]
Dear @yitepeli,

Thank you for uploading the train_ppi_ec.csv.gz file. I have successfully run the model ELISL. However, I found that the outputs are the same for all cancers **(i.e., AUC: 0.5 (0), AUPR: 0.75 (0))**, unmatched the results reported in the paper. Moreover, I further analyzed the reasons for this strange performance. I found that the outputs of ELISL **(using the provided single_cancer_config.json)** are negative (non-SL), which is extremely abnormal. 

I'm wondering if the cause is a misconfiguration of the experiment or a model code version issue. If you find that the current version is incorrect, could you provide the correct version of the code?

Best

**Comment by yitepeli** [comment]
Hi @Seana4rd, 
I have tried to replicate the results over the weekend and for me, it seems to be working fine. Have you tried to call the experiment file with the exact same arguments below for breast cancer (BRCA) or cervix cancer (CESC):
python3.6 src/experiments/single_cancer_experiment.py --model ELRRF --balance_strategy undersample_train_test --grid_search true --cancer BRCA --n_split 10 --process true --threshold 0.5 --exp_file ~/ELISL/data/experiment_configs/single_cancer_config.json

If yes, maybe you can send me your pickled output file privately and I can check what went wrong. Thank you!

**Comment by Seana4rd** [comment]
Hi @yitepeli,
I checked the experimental configuration again to make sure the same arguments as above. However, it is still unchanged.
If possible, could you provide me with your email or other email address so that I can send you the relevant files? Thanks!

**Comment by yitepeli** [comment]
> Hi @yitepeli, I checked the experimental configuration again to make sure the same arguments as above. However, it is still unchanged. If possible, could you provide me with your email or other email address so that I can send you the relevant files? Thanks!

My email is y.i.tepeli@tudelft.nl
You can maybe send the CESC or KIRC pickle files since they are the smallest in size.

Thanks!
